const API_SERVICE_TAGS_TPL = '<%= InterfaceTags %>';
const API_SERVICE_DOC_URL_TPL = '<%= InterfaceDocUrl %>';
const API_SERVICE_SUMMARY_TPL = '<%= InterfaceSummary %>';
const API_SERVICE_DESCRIPTION_TPL = '<%= InterfaceDescription %>';
const API_SERVICE_PARAM_PROPS_TPL = '<%= InterfaceParamsProps %>';
const API_SERVICE_PARAM_TPL = '<%= InterfaceParams %>';
const API_SERVICE_NAME_TPL = '<%= InterfaceName %>';
const API_SERVICE_METHOD_TPL = '<%= InterfaceMethod %>';
const API_SERVICE_URL_TPL = '<%= InterfaceUrl %>';
const API_SERVICE_METHOD_PARAM_TPL = '<%= InterfaceParamsMethod %>';
const API_SERVICE_DEFINITION = '<%= InterfaceDefinition %>';
const API_SERVICE_RETURN_VALUE = '<%= ReturnValueType %>';

const API_DEFINITION_TYPE = '<%= DefinitionType %>';
const API_DEFINITION_NAME = '<%= DefinitionName %>';
const API_DEFINITION_PROPERTY = '<%= DefinitionPropropety %>';

const ENUM_DEFINITION_DESCRIPTION = '<%= EnumDescription %>';
const ENUM_DEFINITION_NAME = '<%= EnumName %>';
const ENUM_DEFINITION_PROPERTIES = '<%= EnumProperties %>';
const ENUM_DEFINITION_INFOS = '<%= EnumInfos %>';
const ENUM_DEFINITION_PROPERTY_TYPE = '<%= EnumPropertyType %>';
const ENUM_DEFINITION_PROPERTY_NAME = '<%= EnumPropertyName %>';
const ENUM_DEFINITION_PROPERTY_VALUE = '<%= EnumPropertyValue %>';
const ENUM_DEFINITION_PROPERTY_DESCRIPTION = '<%= EnumPropertyDescription %>';

const MOCK_REQUEST_METHOD = '<%= MockReqeustMethod %>';
const MOCK_REQUEST_PATH = '<%= MockRequestPath %>';
const MOCK_RESPONSE = '<%= MockResponse %>';

module.exports = {
  API_SERVICE_TAGS_TPL,
  API_SERVICE_DOC_URL_TPL,
  API_SERVICE_SUMMARY_TPL,
  API_SERVICE_DESCRIPTION_TPL,
  API_SERVICE_PARAM_PROPS_TPL,
  API_SERVICE_PARAM_TPL,
  API_SERVICE_METHOD_PARAM_TPL,
  API_SERVICE_NAME_TPL,
  API_SERVICE_URL_TPL,
  API_SERVICE_METHOD_TPL,
  API_SERVICE_DEFINITION,
  API_SERVICE_RETURN_VALUE,
  API_DEFINITION_TYPE,
  API_DEFINITION_NAME,
  API_DEFINITION_PROPERTY,
  ENUM_DEFINITION_DESCRIPTION,
  ENUM_DEFINITION_NAME,
  ENUM_DEFINITION_PROPERTIES,
  ENUM_DEFINITION_INFOS,
  ENUM_DEFINITION_PROPERTY_TYPE,
  ENUM_DEFINITION_PROPERTY_NAME,
  ENUM_DEFINITION_PROPERTY_VALUE,
  ENUM_DEFINITION_PROPERTY_DESCRIPTION,
  MOCK_REQUEST_METHOD,
  MOCK_REQUEST_PATH,
  MOCK_RESPONSE
};
